name: GitHub Repo Sync
author: Wei He <github@weispot.com>
description: ⤵️ Sync two repositories using GitHub Actions
branding:
  icon: 'git-branch'
  color: 'gray-dark'
inputs:
  source_repo:
    description: GitHub public repo slug or full https clone url (with access_token if needed)
    required: true
  source_branch:
    description: Branch name to sync from
    required: true
  destination_branch:
    description: Branch name to sync to in this repo
    required: true
  source_host:
    description: Hostname of the source repo if different from github.com. If set, the source_repo must be repo slug.
    required: false
  destination_host:
    description: Hostname of the destination repo if different from github.com
    required: false
  destination_repo:
    description: Git repo slug. If not provided, the source_repo will be used.
    required: false
  destination_user:
    description: GitHub username for pushing to the destination repo. If not provided, the default GITHUB_ACTOR will be used.
    required: false
  destination_token:
    description: GitHub token secret for pushing to the destination repo. If not provided, the default GITHUB_TOKEN will be used.
    required: false
  github_token:
    description: GitHub token secret for accessing the source repo.
    required: false
  sync_tags:
    description: Should tags also be synced
    required: false
runs:
  using: 'docker'
  image: docker://ghcr.io/repo-sync/github-sync:v2.3.0
  env:
    GITHUB_TOKEN: ${{ inputs.github_token }}
    SYNC_TAGS: ${{ inputs.sync_tags }}
    SOURCE_HOST: ${{ inputs.source_host }}
    SOURCE_TOKEN: ${{ inputs.github_token }}
    SOURCE_USER: ${{ github.actor }}
    DESTINATION_HOST: ${{ inputs.destination_host }}
    DESTINATION_USER: ${{ inputs.destination_user }}
    DESTINATION_TOKEN: ${{ inputs.destination_token }}
    DESTINATION_REPO: ${{ inputs.destination_repo }}
  args:
    - ${{ inputs.source_repo }}
    - ${{ inputs.source_branch }}:${{ inputs.destination_branch }}
